# Generated by Django 4.0.6 on 2026-05-29 06:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('backend', '0002_file_uploaded_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='DbLinkProjectConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('webclientUrl', models.CharField(blank=True, default='', max_length=2048)),
                ('lookupUrlTemplate', models.CharField(blank=True, default='', max_length=2048)),
                ('createNewUrlTemplate', models.CharField(blank=True, default='', max_length=2048)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='db_link_config', to='backend.project')),
            ],
        ),
        migrations.CreateModel(
            name='DbLinkPointsFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='backend.file')),
                ('modelData', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='db_link_points_file', to='backend.modeldata')),
            ],
        ),
    ]
